services:
  ur_ros2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ur_ros2
    ports:
      - 50002:50002
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - ROBOT_IP=${ROBOT_IP:-172.16.191.143}  # Default IP for real robot, override with environment
    volumes:
      - ./src/my_packages:/ros2_ws/src/my_packages
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/root/.Xauthority:ro
    network_mode: host
    privileged: true
    tty: true
